package com.softcell.gonogo.model.request;

public enum ActionName 
{
	
    SMS_SERVICE, VALIDATION, PARTIAL_SAVE, POST_IPA, STP, IMAGE_UPLOAD, DELIVERY_ORDER, DIGITIZATION, SERIAL_NUMBER_VALIDATION, RE_APRAISAL, RE_INITIATE, REPORT_DOWNLOAD, LOS_DATA_ENTRY_INTERFACE, AWS_INTERFACE, RELIANCE_INTERFACE, LOG_CHANGE,
    MASTER_UPLOAD, SENT_EMAIL, ALL_BRANCH, TVR_DATA_PUSH, ALL_RELIANCE_DEALER, GENERATE_PROSPECTNUM, GENERATE_AGGREMENTNUM, DMS_DOC_PUSH, TKIL_INTERFACE,KHOSLA_INTERFACE,
    SEND_DISBURSEMENT_SMS, SEND_DONWLOAD_LINK_SMS, SEND_EW_SMS, SEND_APPROVAL_SMS, MB_RESPONSE_SAVE, ALL_TKIL_DEALER, SOBRE_RESPONSE_SAVE, AUTO_CANCEL_DEDUPE_CASE, SEND_DEDUPE_INFO_TO_SOBRE,
    PUSH_DATA_TO_SAATHI_SERVICE,DIGI_FORM_SAVE_AT_INVOICE_TIME, LOS_MB_DATA_PUSH,AUTO_DECLINE_DEDUPE_CASE,IMEI_ROLLBACK,MULTIPRODUCT,
    DO_RESET,MODIFY_APP_STAGE_STATUS,PUSH_DATA_TO_MIFIN,PUSH_DATA_TO_LMS,BULK_UPDATE_DECISION, EVALUATE_INSURANCE_POLICY, POSIDEX_FINDCUSTOMER,
    POSIDEX_ADDCUSTOMER, MASTER_DEDUPE, EXPOSURE

}
